### ISSUE TITLE
Deploy to salesforce is not working

### ISSUE THREAD

**Issue by chandra2ravi** [financialforcedev/ffhttp-dropbox#1]
Please find the below errors.

Deployment Started
Status: Queued 
Status: Completed 
Deployment Complete
Failures:
classes/ffhttp_Dropbox.cls(41,24):Invalid type: ffhttp_Client.Credentials
classes/ffhttp_DropboxFileOperations.cls(40,38):Dependent class is invalid and needs recompilation:
ffhttp_Dropbox: line 41, column 24: Invalid type: ffhttp_Client.Credentials
classes/ffhttp_DropboxFiles.cls(40,29):Dependent class is invalid and needs recompilation:
ffhttp_Dropbox: line 41, column 24: Invalid type: ffhttp_Client.Credentials
classes/ffhttp_DropboxModelAccountInfo.cls(50,66):Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxModelCopyRef.cls(39,62):Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxModelDelta.cls(62,60):Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxModelFile.cls(50,59):Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxModelLongpollDelta.cls(39,68):Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxModelTest.cls(37,60):Dependent class is invalid and needs recompilation:
ffhttp_DropboxModelAccountInfo: line 50, column 66: Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxModelUploadChunk.cls(42,66):Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxModelUrl.cls(39,58):Invalid type: ffhttp_AbstractJsonSerializable
classes/ffhttp_DropboxResource.cls(57,10):Dependent class is invalid and needs recompilation:
ffhttp_Dropbox: line 41, column 24: Invalid type: ffhttp_Client.Credentials
classes/ffhttp_DropboxTest.cls(37,3):Dependent class is invalid and needs recompilation:
ffhttp_DropboxAccounts: line 40, column 32: Dependent class is invalid and needs recompilation:
ffhttp_Dropbox: line 41, column 24: Invalid type: ffhttp_Client.Credentials
classes/ffhttp_DropboxAccounts.cls(40,32):Dependent class is invalid and needs recompilation:
ffhttp_Dropbox: line 41, column 24: Invalid type: ffhttp_Client.Credentials

**Comment by mwoodcertinia** [comment]
Can you check that you have deployed the Core library found at https://github.com/financialforcedev/ffhttp-core?

From the errors it looks like this library is missing.

**Comment by jg-mahendra** [comment]
Hi Matt, I am getting an error "The connector Dropbox API for User has not been authorized".
This happened when I tried to validate the connection from Test Harness tab.

It would be great if you can help on this.

Thanks,
Mahendra
