### ISSUE TITLE
ffhttp_Client file is missing

### ISSUE THREAD

**Issue by krishnabidwai** [financialforcedev/ffhttp-dropbox#3]
Hello, 

I want to use ffhttp_DropboxFileOperations cls which extends ffhttp_DropboxResource class in which there is instance of ffhttp_Dropbox class which extends to **ffhttp_Client.AbstractClient** which is missing in the folder. 

Please share the file asap.

Thanks in advance!!

**Comment by mwoodcertinia** [comment]
The `ffhttp_Client.AbstractClient` class forms part of the ffhttp_core library which can be found [here](https://github.com/financialforcedev/ffhttp-core). This library needs to be deployed before any of the Dropbox components.

All the steps required can be found in the configuration section of the readme [(here)](https://github.com/financialforcedev/ffhttp-dropbox#configuration).
